### ISSUE TITLE
Websocket in a supervisor says discarding unexpected message

### ISSUE THREAD

**Issue by rockerBOO** [lpil/nerf#10]
Trying to put the websocket connection in a worker under a supervisor and getting this warning (which is also eating the messages).

```
=WARNING REPORT==== 6-Jan-2024::21:35:11.187481 ===
Actor discarding unexpected message: GunWs(//erl(<0.151.0>), //erl(#Ref<0.1082928177.90701828.188266>), Text(":tmi.twitch.tv CAP * ACK :twitch.tv/membership twitch.tv/tags twitch.tv/commands\r\n"))
```

Code works without a twitch account.

```gleam
import gleam/otp/supervisor
import gleam/otp/actor
import nerf/websocket
import gleam/erlang/process
import gleam/io

pub fn supervisor_test() {
  let worker =
    supervisor.worker(fn(_arguments) {
      let assert Ok(conn) =
        websocket.connect("irc-ws.chat.twitch.tv", "/", 80, [])
      websocket.send(
        conn,
        "CAP REQ :twitch.tv/membership twitch.tv/tags twitch.tv/commands",
      )

      let _ = actor.start(conn, fn(_msg, state) { actor.continue(state) })
    })

  let assert Ok(_) =
    supervisor.start(fn(children) {
      children
      |> supervisor.add(worker)
    })

  process.sleep(1000)
}

pub fn non_supervisor_test() {
  let assert Ok(conn) = websocket.connect("irc-ws.chat.twitch.tv", "/", 80, [])
  websocket.send(
    conn,
    "CAP REQ :twitch.tv/membership twitch.tv/tags twitch.tv/commands",
  )

  let assert Ok(y) = websocket.receive(conn, 500)

  io.debug(y)
}
```

My goal is to have a supervised websocket worker which listens for messages. So if the websocket crashes or the message handlers crash it will reconnect. Gun says they are supervising each message so I'm not sure if this is overkill. 

Supervisor 
-> WebsocketWorker
   -> MessageHandler (x8)

I need async worker handlers because of 'expensive' work that may take upwards of 30 seconds but want to continue handling messages as they come in. 

I understand this project is tenuous to be deprecated but I think it's the only one handling websockets currently but I can poke at it if there is some direction. Thank you.

**Comment by lpil** [comment]
You have made the supervisor the websocket process rather than the worker. The supervisor is not expecting to handle these messages so it logs warnings about them.

**Comment by rockerBOO** [comment]
Ok, I can see how that is happening in terms of the warning but not sure how I am making my websocket process the supervisor here since i'm adding it as a worker to a supervisor. Closing this as it's unrelated to this library though. 

Thank you for pointing out the issue which I can work with in debugging.
